# Generated by Django 5.2.5 on 2025-12-09 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AestheticRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Cyberpunk Melt'", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Describe the visual effect"
                    ),
                ),
                (
                    "threshold_low",
                    models.FloatField(
                        default=0.25, help_text="Lower brightness threshold (0-1)"
                    ),
                ),
                (
                    "threshold_high",
                    models.FloatField(
                        default=0.8, help_text="Upper brightness threshold (0-1)"
                    ),
                ),
                (
                    "sort_direction",
                    models.CharField(
                        choices=[("H", "Horizontal"), ("V", "Vertical")],
                        default="V",
                        max_length=1,
                    ),
                ),
                (
                    "sort_by",
                    models.CharField(
                        choices=[
                            ("L", "Luminosity"),
                            ("H", "Hue"),
                            ("S", "Saturation"),
                            ("R", "Red Channel"),
                            ("G", "Green Channel"),
                            ("B", "Blue Channel"),
                        ],
                        default="L",
                        max_length=1,
                    ),
                ),
                (
                    "interval_random",
                    models.BooleanField(
                        default=False, help_text="Randomize sorting intervals"
                    ),
                ),
                (
                    "reverse_sort",
                    models.BooleanField(
                        default=False, help_text="Sort in descending order"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Allow others to use this recipe"
                    ),
                ),
                ("times_used", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Aesthetic Recipe",
                "verbose_name_plural": "Aesthetic Recipes",
                "ordering": ["-times_used", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArtPiece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("original_image", models.ImageField(upload_to="originals/")),
                (
                    "processed_image",
                    models.ImageField(blank=True, null=True, upload_to="processed/"),
                ),
                (
                    "export_story",
                    models.ImageField(
                        blank=True, null=True, upload_to="exports/story/"
                    ),
                ),
                (
                    "export_post",
                    models.ImageField(blank=True, null=True, upload_to="exports/post/"),
                ),
                ("custom_threshold_low", models.FloatField(blank=True, null=True)),
                ("custom_threshold_high", models.FloatField(blank=True, null=True)),
                ("custom_sort_direction", models.CharField(blank=True, max_length=1)),
                ("custom_sort_by", models.CharField(blank=True, max_length=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "recipe_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="art_pieces",
                        to="editor.aestheticrecipe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="art_pieces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Art Piece",
                "verbose_name_plural": "Art Pieces",
                "ordering": ["-created_at"],
            },
        ),
    ]
